### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by kristianmandrup** [salamynder/bs-mithril-test#1]
I'd like to experiment with using Mithril from ReasonML. Care to join me?

**Comment by salamynder** [comment]
tl;dr: I do not maintain this project atm and joining, though I'd like, is also difficult..blabla...

Hi Kristian,
sorry took me so long, but I needed to rest my hands from typing stuff...
I'd really like to join, but I'm very much bound by other things right now.
Also I rather stay more at OCaml, because I think I have to see more of it in future, though I like ReasonMLs care for syntax, which seems a mix between Haskell and Javascript :) (damn semicolon!)
Mithril and its community is a special island of practical reason, anyway.. :)
Good luck exploring!

**Comment by salamynder** [comment]
Just a note about architecture (as I skimmed my code here), what do you think of:
https://github.com/OvermindDL1/bucklescript-tea
?
Before Mithril I tried Elm, but couldn't do shit. :) However the Elm architecture itself is quite intriguing, I find.

**Comment by kristianmandrup** [comment]
Yeah, I'd like to do ReasonML with Meiosis (pattern - similar to, but much better than Elm). Meiosis can work with any View layer, Router, State manager etc. Connects all the "dots" in a super amazing pattern, based on streams, similar to CycleJS. 

Anyways, I've since given up on ReasonML (too difficult to do bindings, little community interest or assistance...). Now I've shifted to F# and Fable (F# -> Javascript) with Elmish (essentially Elm pattern for F#). F# is also in the OCaml family, but much easier to use.

Cheers. 

PS: I started a `bs-mithril-stream` project (on my github) and got a little assistance on how to do the bindings for that one...
